local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "Senjitsu: HalBackground", [[Interface\Addons\SharedMedia_Senjitsu\background\HalBackground.tga]]) 
LSM:Register("background", "Senjitsu: HalBackgroundA", [[Interface\Addons\SharedMedia_Senjitsu\background\HalBackgroundA.tga]]) 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "Senjitsu: AllBlackBorder", [[Interface\Addons\SharedMedia_Senjitsu\border\AllBlackBorder.tga]]) 
LSM:Register("border", "Senjitsu: HalBorder", [[Interface\Addons\SharedMedia_Senjitsu\border\HalBorder.tga]]) 
LSM:Register("border", "Senjitsu: Sexymapsolid", [[Interface\Addons\SharedMedia_Senjitsu\border\Sexymapsolid.tga]]) 

-- -----
--   FONT
-- -----
LSM:Register("font", "Senjitsu: SABF", [[Interface\Addons\SharedMedia_Senjitsu\font\ABF.ttf]]) 
LSM:Register("font", "Senjitsu: AccidentalPresidency", [[Interface\Addons\SharedMedia_Senjitsu\font\AccidentalPresidency.ttf]]) 
--LSM:Register("font", "Adventure", [[Interface\Addons\SharedMedia_Senjitsu\font\Adventure.ttf]]) 
LSM:Register("font", "Senjitsu: AvantGardeCTT", [[Interface\Addons\SharedMedia_Senjitsu\font\AvantGardeCTT.ttf]]) 
LSM:Register("font", "Senjitsu: AvantGardeGothicLTMedium", [[Interface\Addons\SharedMedia_Senjitsu\font\AvantGardeGothicLTMedium.ttf]]) 
LSM:Register("font", "Senjitsu: BigNoodleTitling-Oblique", [[Interface\Addons\SharedMedia_Senjitsu\font\BigNoodleTitling-Oblique.ttf]]) 
LSM:Register("font", "Senjitsu: BigNoodleTitling", [[Interface\Addons\SharedMedia_Senjitsu\font\BigNoodleTitling.ttf]]) 
LSM:Register("font", "Senjitsu: BigNoodleToo", [[Interface\Addons\SharedMedia_Senjitsu\font\BigNoodleToo.ttf]]) 
LSM:Register("font", "Senjitsu: BigNoodleTooOblique", [[Interface\Addons\SharedMedia_Senjitsu\font\BigNoodleTooOblique.ttf]]) 
LSM:Register("font", "Senjitsu: BlackChancery", [[Interface\Addons\SharedMedia_Senjitsu\font\BlackChancery.ttf]]) 
--LSM:Register("font", "Emblem", [[Interface\Addons\SharedMedia_Senjitsu\font\Emblem.ttf]]) 
LSM:Register("font", "Senjitsu: Enigma2", [[Interface\Addons\SharedMedia_Senjitsu\font\Enigma2.ttf]]) 
--LSM:Register("font", "GoJuOn", [[Interface\Addons\SharedMedia_Senjitsu\font\GoJuOn.ttf]]) 
LSM:Register("font", "Senjitsu: gothic", [[Interface\Addons\SharedMedia_Senjitsu\font\gothic.ttf]]) 
LSM:Register("font", "Senjitsu: Microgramma", [[Interface\Addons\SharedMedia_Senjitsu\font\Microgramma.ttf]]) 
LSM:Register("font", "Senjitsu: Movie_Poster-Bold", [[Interface\Addons\SharedMedia_Senjitsu\font\Movie_Poster-Bold.ttf]]) 
LSM:Register("font", "Senjitsu: Neuropol", [[Interface\Addons\SharedMedia_Senjitsu\font\Neuropol.ttf]]) 
LSM:Register("font", "Senjitsu: normal_font", [[Interface\Addons\SharedMedia_Senjitsu\font\normal_font.ttf]]) 
--LSM:Register("font", "Pepsi", [[Interface\Addons\SharedMedia_Senjitsu\font\Pepsi.ttf]]) 
--LSM:Register("font", "Porky", [[Interface\Addons\SharedMedia_Senjitsu\font\Porky.ttf]]) 
--LSM:Register("font", "rm_midse", [[Interface\Addons\SharedMedia_Senjitsu\font\rm_midse.ttf]]) 
--SM:Register("font", "segoeui", [[Interface\Addons\SharedMedia_Senjitsu\font\segoeui.ttf]]) 
--LSM:Register("font", "SteelFish", [[Interface\Addons\SharedMedia_Senjitsu\font\SteelFish.ttf]]) 
--LSM:Register("font", "Tempest", [[Interface\Addons\SharedMedia_Senjitsu\font\Tempest.ttf]]) 
--LSM:Register("font", "Tw_Cen_MT_Bold", [[Interface\Addons\SharedMedia_Senjitsu\font\Tw_Cen_MT_Bold.ttf]]) 
--LSM:Register("font", "uf_font", [[Interface\Addons\SharedMedia_Senjitsu\font\uf_font.ttf]]) 
--LSM:Register("font", "Ultima_Campagnoli", [[Interface\Addons\SharedMedia_Senjitsu\font\Ultima_Campagnoli.ttf]]) 
LSM:Register("font", "Senjitsu: Visitor1", [[Interface\Addons\SharedMedia_Senjitsu\font\Visitor1.ttf]]) 
LSM:Register("font", "Senjitsu: Visitor2", [[Interface\Addons\SharedMedia_Senjitsu\font\Visitor2.ttf]]) 
--LSM:Register("font", "Yellowjacket", [[Interface\Addons\SharedMedia_Senjitsu\font\Yellowjacket.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "Senjitsu: detected-nearby", [[Interface\Addons\SharedMedia_Senjitsu\sound\detected-nearby.mp3]])
LSM:Register("sound", "Senjitsu: detected-stealth", [[Interface\Addons\SharedMedia_Senjitsu\sound\detected-stealth.mp3]])
LSM:Register("sound", "Senjitsu: cn_bao4_zha4", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_bao4_zha4.mp3]])
LSM:Register("sound", "Senjitsu: cn_ci4", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_ci4.mp3]])
LSM:Register("sound", "Senjitsu: cn_dian4", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_dian4.mp3]])
LSM:Register("sound", "Senjitsu: cn_fang2", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_fang2.mp3]])
LSM:Register("sound", "Senjitsu: cn_fang4_jian4", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_fang4_jian4.mp3]])
LSM:Register("sound", "Senjitsu: cn_sha1", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_sha1.mp3]])
LSM:Register("sound", "Senjitsu: cn_shao1", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_shao1.mp3]])
LSM:Register("sound", "Senjitsu: cn_she4", [[Interface\Addons\SharedMedia_Senjitsu\sound\cn_she4.mp3]])
LSM:Register("sound", "Senjitsu: Multi Blackarrow", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\multi_blackarrow.mp3]])
LSM:Register("sound", "Senjitsu: Blackarrow Cast 01", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\spell_hu_blackarrow_cast_01.ogg]])
LSM:Register("sound", "Senjitsu: Blackarrow Cast 02", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\spell_hu_blackarrow_cast_02.ogg]])
LSM:Register("sound", "Senjitsu: Blackarrow Cast 03", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\spell_hu_blackarrow_cast_03.ogg]])
LSM:Register("sound", "Senjitsu: Blackarrow Cast 04", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\spell_hu_blackarrow_cast_04.ogg]])
LSM:Register("sound", "Senjitsu: Blackarrow Cast 05", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\spell_hu_blackarrow_cast_05.ogg]])
LSM:Register("sound", "Senjitsu: Blackarrow Cast 06", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\spell_hu_blackarrow_cast_06.ogg]])
LSM:Register("sound", "Senjitsu: Black Barbed Shot", [[Interface\Addons\SharedMedia_Senjitsu\sound\hunter\black_barbed_shot.mp3]])
LSM:Register("sound", "Senjitsu: Vampire", [[Interface\Addons\SharedMedia_Senjitsu\sound\MON_Vampire_Female_fidget0_00_157002.ogg]])
LSM:Register("sound", "Senjitsu: Wham!", 566946)
LSM:Register("sound", "Senjitsu: Invoke Xuen", 623942)
LSM:Register("sound", "Senjitsu: Aimed Shot", 1590095)

LSM:Register("sound", "Senjitsu: guinevere_kof_02", [[Interface\Addons\SharedMedia_Senjitsu\sound\guinevere_kof_02.mp3]])
LSM:Register("sound", "Senjitsu: harley_female_shoot_ulti", [[Interface\Addons\SharedMedia_Senjitsu\sound\harley_female_shoot_ulti.mp3]])
LSM:Register("sound", "Senjitsu: nana_shoot_ulti", [[Interface\Addons\SharedMedia_Senjitsu\sound\nana_shoot_ulti.mp3]])

--LSM:Register("sound", "Rubber Ducky",  566121)
--LSM:Register("sound", "Cartoon FX",	   566543)
--LSM:Register("sound", "Explosion", 	   566982)
--LSM:Register("sound", "Shing!", 	   566240)
--LSM:Register("sound", "Simon Chime",   566076)
--LSM:Register("sound", "War Drums", 	   567275)
--LSM:Register("sound", "Cheer", 		   567283)
--LSM:Register("sound", "Humm", 		   569518)
--LSM:Register("sound", "Short Circuit", 568975)
--LSM:Register("sound", "Fel Portal",    569215)
--LSM:Register("sound", "Fel Nova", 	   568582)
--LSM:Register("sound", "You Will Die!", 546633)

--LSM:Register("sound", "Die!", 		   551339)
--LSM:Register("sound", "You Fail!", 	   553345)

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "HalA", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalA.tga]]) 
LSM:Register("statusbar", "HalB", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalB.tga]]) 
LSM:Register("statusbar", "HalC", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalC.tga]]) 
LSM:Register("statusbar", "HalD", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalD.tga]]) 
LSM:Register("statusbar", "HalE", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalE.tga]]) 
LSM:Register("statusbar", "HalF", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalF.tga]]) 
LSM:Register("statusbar", "HalG", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalG.tga]]) 
LSM:Register("statusbar", "HalH", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalH.tga]]) 
LSM:Register("statusbar", "HalI", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalI.tga]]) 
LSM:Register("statusbar", "HalJ", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalJ.tga]]) 
LSM:Register("statusbar", "HalK", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalK.tga]]) 
LSM:Register("statusbar", "HalL", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalL.tga]]) 
LSM:Register("statusbar", "HalM", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalM.tga]]) 
LSM:Register("statusbar", "HalN", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalN.tga]]) 
LSM:Register("statusbar", "HalO", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalO.tga]]) 
LSM:Register("statusbar", "HalP", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalP.tga]]) 
LSM:Register("statusbar", "HalQ", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalQ.tga]]) 
LSM:Register("statusbar", "HalR", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalR.tga]]) 
LSM:Register("statusbar", "HalS", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalS.tga]]) 
LSM:Register("statusbar", "HalT", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalT.tga]]) 
LSM:Register("statusbar", "HalU", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalU.tga]]) 
LSM:Register("statusbar", "HalV", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\HalV.tga]]) 
LSM:Register("statusbar", "Cast1", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\Cast1.tga]]) 
LSM:Register("statusbar", "Cast2", [[Interface\Addons\SharedMedia_Senjitsu\statusbar\Cast2.tga]]) 
